### ISSUE TITLE
Integrate the Image Processing API

### ISSUE THREAD

**Issue by rushabh55** [rushabh55/NaviTag-iOS#3]
API is open sourced at https://github.com/BradLarson/GPUImage

**Comment by SidoPillai** [comment]
- [x] Take the image from the device. (Siddesh)
- [x] Image Process. @rushabh55 
- [ ] Send to the server. @rushabh55 
- [x] Upload in the game. (Siddesh)
- [ ] Update the server after adding Image @sapna4g 
- [ ] Update the game data in the server @sapna4g
