### ISSUE TITLE
Get the updated files from here. 

### ISSUE THREAD

**Issue by SidoPillai** [rushabh55/NaviTag-iOS#6]
https://github.com/sidd4698/IOS-App---Treasure-Hunt

**Comment by SidoPillai** [comment]
@rushabh55 @sapna4g

**Comment by rushabh55** [comment]
Ill merge it this time, but next time you commit on the main repo.
Irrespective of conflicts. If you want make a new branch. But no new repos.

**Comment by SidoPillai** [comment]
alright
